server:
  port: 20001


spring:
  ##########################################################################
  ###数据源信息配置
  ##########################################################################
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://119.29.119.221/office?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
      username: lzc
      password: luozc1993.
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  ##########################################################################
  ###JPA持久化配置
  ##########################################################################
  jpa:
    #指定数据库类型
    database: MYSQL
    #指定是否需要在日志中显示sql语句
    show-sql: true
    #指定自动创建|更新|验证数据库表结构等配置，配置成update
    #表示如果数据库中存在持久化类对应的表则不创建，不存在则创建对应的表
    hibernate:
      ddl-auto: update
      #指定命名策略
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy




mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.luozc.domain

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


